import "element-plus/dist/index.css";
import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import withUUID from "vue-uuid";
const pinia = createPinia();
const app = createApp(App);
import ElementPlus from "element-plus";
import router from "@/router";
app.use(pinia);
app.use(router);
app.use(ElementPlus);
app.use(withUUID);
app.mount("#app");
